In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')

In [19]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [20]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [21]:
def tokenize(text:str):
  text=  text.lower()
  text= text.replace(',','')
  text= text.replace('?','')
  text= text.replace('!','')
  return text.split()

In [9]:
# df.apply(lambda x: tokenize(x['question']),axis=1)

0                  [what, is, the, capital, of, france]
1                 [what, is, the, capital, of, germany]
2              [who, wrote, 'to, kill, a, mockingbird']
3     [what, is, the, largest, planet, in, our, sola...
4     [what, is, the, boiling, point, of, water, in,...
                            ...
85               [who, directed, the, movie, 'titanic']
86    [which, superhero, is, also, known, as, the, d...
87                 [what, is, the, capital, of, brazil]
88    [which, fruit, is, known, as, the, king, of, f...
89    [which, country, is, known, for, the, eiffel, ...
Length: 90, dtype: object

In [22]:
vocab = {
    '<UNK>':0
}

In [23]:
def build_vocab(row):
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])

  merged_tokens = tokenized_question + tokenized_answer

  for token in merged_tokens:

    if token not in vocab:
      vocab[token] = len(vocab)

In [24]:
df.apply(build_vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [25]:
len(vocab)

326

In [26]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 "'to": 12,
 'kill': 13,
 'a': 14,
 "mockingbird'": 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 "'1984'": 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299792458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 "'starry": 130,
 "night'": 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'to': 143,
 'step': 144,
 'moon': 145,
 'armstrong': 146,
 'main': 147,
 'ingredient': 148,
 'guacamole': 149,
 'avocado': 150,
 'sides': 151,
 'does': 152,
 'hexagon': 153,
 'have': 154,
 '6': 155,
 'china': 156,
 'yuan': 157,
 "'pride": 158,
 'and': 159,
 "prejudice'": 160,
 'jane-austen': 161,
 'iron': 162,
 'fe': 163,
 'hardest': 164,
 'natural': 165,
 'substance': 166,
 'diamond': 167,
 'continent': 168,
 'by': 169,
 'area': 170,
 'asia': 171,
 'president': 172,
 'states': 173,
 'george-washington': 174,
 'bird': 175,
 'its': 176,
 'ability': 177,
 'mimic': 178,
 'sounds': 179,
 'parrot': 180,
 'longest-running': 181,
 'animated': 182,
 'tv': 183,
 'show': 184,
 'simpsons': 185,
 'vaticancity': 186,
 'most': 187,
 'moons': 188,
 'saturn': 189,
 "'romeo": 190,
 "juliet'": 191,
 'shakespeare': 192,
 "earth's": 193,
 'atmosphere': 194,
 'nitrogen': 195,
 'bones': 196,
 'adult': 197,
 'human': 198,
 'body': 199,
 '206': 200,
 'metal': 201,
 'liquid': 202,
 'at': 203,
 'room': 204,
 'temperature': 205,
 'mercury': 206,
 'russia': 207,
 'moscow': 208,
 'electricity': 209,
 'benjamin-franklin': 210,
 'second-largest': 211,
 'land': 212,
 'color': 213,
 'ripe': 214,
 'banana': 215,
 'yellow': 216,
 'month': 217,
 '28': 218,
 'days': 219,
 'common': 220,
 'february': 221,
 'study': 222,
 'living': 223,
 'organisms': 224,
 'called': 225,
 'biology': 226,
 'home': 227,
 'great': 228,
 'wall': 229,
 'bees': 230,
 'collect': 231,
 'from': 232,
 'flowers': 233,
 'nectar': 234,
 'opposite': 235,
 "'day'": 236,
 'night': 237,
 'south': 238,
 'korea': 239,
 'seoul': 240,
 'bulb': 241,
 'edison': 242,
 'humans': 243,
 'breathe': 244,
 'survival': 245,
 'oxygen': 246,
 '144': 247,
 '12': 248,
 'pyramids': 249,
 'giza': 250,
 'egypt': 251,
 'sea': 252,
 'creature': 253,
 'eight': 254,
 'arms': 255,
 'octopus': 256,
 'holiday': 257,
 'celebrated': 258,
 'december': 259,
 '25': 260,
 'christmas': 261,
 'yen': 262,
 'legs': 263,
 'spider': 264,
 'sport': 265,
 'uses': 266,
 'net': 267,
 'ball': 268,
 'hoop': 269,
 'basketball': 270,
 'kangaroos': 271,
 'female': 272,
 'minister': 273,
 'uk': 274,
 'margaretthatcher': 275,
 'fastest': 276,
 'animal': 277,
 'cheetah': 278,
 'periodic': 279,
 'table': 280,
 'spain': 281,
 'madrid': 282,
 'closest': 283,
 'sun': 284,
 'father': 285,
 'computers': 286,
 'charlesbabbage': 287,
 'mexico': 288,
 'mexicocity': 289,
 'colors': 290,
 'rainbow': 291,
 'musical': 292,
 'instrument': 293,
 'black': 294,
 'white': 295,
 'keys': 296,
 'piano': 297,
 'americas': 298,
 '1492': 299,
 'christophercolumbus': 300,
 'disney': 301,
 'character': 302,
 'long': 303,
 'nose': 304,
 'grows': 305,
 'it': 306,
 'when': 307,
 'lying': 308,
 'pinocchio': 309,
 'directed': 310,
 'movie': 311,
 "'titanic'": 312,
 'jamescameron': 313,
 'superhero': 314,
 'also': 315,
 'dark': 316,
 'knight': 317,
 'batman': 318,
 'brasilia': 319,
 'fruit': 320,
 'king': 321,
 'fruits': 322,
 'mango': 323,
 'eiffel': 324,
 'tower': 325}

In [28]:
def text_to_indices(text,vocab):
  indexed_text = []
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [29]:
text_to_indices('what is your name',vocab)

[1, 2, 0, 0]

In [30]:
import torch
from torch.utils.data import Dataset, DataLoader

In [31]:
class QADataset(Dataset):

  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):

    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [32]:
dataset = QADataset(df, vocab)

In [33]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [34]:
for question, answer in dataloader:
  print(question, answer[0])

tensor([[  1,   2,   3,  37,  38,  39, 162]]) tensor([163])
tensor([[10, 29,  3, 30, 31]]) tensor([32])
tensor([[ 42, 252, 253, 118, 254, 255]]) tensor([256])
tensor([[ 42,   2,   3, 276, 212, 277]]) tensor([278])
tensor([[ 42, 137,   2, 227, 143,   3, 228, 229]]) tensor([156])
tensor([[ 10, 140,   3, 141, 142, 143, 144,  83,   3, 145]]) tensor([146])
tensor([[10, 75, 76]]) tensor([77])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[ 42, 137,   2,  62,  39,   3, 324, 325]]) tensor([6])
tensor([[  1,   2,   3, 164, 165, 166,  83,  84]]) tensor([167])
tensor([[  1,  87, 230, 231, 232, 233]]) tensor([234])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[ 42, 168,   2,   3,  17, 169, 170]]) tensor([171])
tensor([[ 42,  18,   2,   3, 283, 143,   3, 284]]) tensor([206])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([36])
tensor([[ 78,  79, 196,  81,  19,   3, 197, 198, 199]]) tensor([200])
tensor([[  1,   2,   3, 213,   5,  14, 214, 215]]) tensor([216])
tensor([[  1,   2,   3, 235,   5, 236]]) tensor([237])
tensor([[ 42,  18, 118,   3, 187, 188]]) tensor([189])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([116])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([319])
tensor([[ 42, 314,   2, 315,  62,  63,   3, 316, 317]]) tensor([318])
tensor([[  1,   2,   3, 147,  86,  19, 193, 194]]) tensor([195])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([61])
tensor([[ 42, 301, 302, 118,  14, 303, 304, 159, 305, 306, 307, 308]]) tensor([309])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([95])
tensor([[ 42, 217, 118, 218, 219,  19,  14, 220,  43]]) tensor([221])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([36])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
tensor([[  1,   2,   3,   4,   5, 288]]) tensor([289])
tensor([[  1,   2,   3, 141, 117,  83,   3, 279, 280]]) tensor([121])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([58])
tensor([[  1,   2,   3,   4,   5, 207]]) tensor([208])
tensor([[ 42, 257,   2, 258,  83, 259, 260]]) tensor([261])
tensor([[  1,   2,   3, 147, 148,  19, 149]]) tensor([150])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([68])
tensor([[ 78,  79, 290,  81,  19,  14, 291]]) tensor([85])
tensor([[ 10,  96,   3, 104, 241]]) tensor([242])
tensor([[ 42, 265, 266,  14, 267, 268, 159, 269]]) tensor([270])
tensor([[ 42, 101,   2,   3,  17]]) tensor([102])
tensor([[ 42, 292, 293, 118, 294, 159, 295, 296]]) tensor([297])
tensor([[ 10,  75, 111]]) tensor([112])
tensor([[ 42,   2,   3, 211, 137, 169, 212, 170]]) tensor([113])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([110])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
tensor([[ 10, 140,   3, 141, 272,  93, 273,   5,   3, 274]]) tensor([275])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([85])
tensor([[  1,   2,   3,  33,  34,   5, 247]]) tensor([248])
tensor([[ 42, 175,   2,  62,  39, 176, 177, 143, 178, 179]]) tensor([180])
tensor([[ 10,  29, 130, 131]]) tensor([132])
tensor([[10, 96,  3, 97]]) tensor([98])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([124])
tensor([[ 42, 201,   2,  14, 202, 203, 204, 205]]) tensor([206])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([91])
tensor([[ 78,  79, 263, 152,  14, 264, 154]]) tensor([36])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([100])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
tensor([[  1,   2,   3,   4,   5, 238, 239]]) tensor([240])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([186])
tensor([[ 42, 320,   2,  62,  63,   3, 321,   5, 322]]) tensor([323])
tensor([[ 42, 137, 118,   3, 249,   5, 250]]) tensor([251])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([262])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([121])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([65])
tensor([[ 78,  79, 151, 152,  14, 153, 154]]) tensor([155])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([53])
tensor([[ 10, 140,   3, 141, 172,   5,   3,  70, 173]]) tensor([174])
tensor([[ 42, 137,   2, 138,  39, 176, 271]]) tensor([99])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[  1,   2,   3, 222,   5, 223, 224, 225]]) tensor([226])
tensor([[ 10, 310,   3, 311, 312]]) tensor([313])
tensor([[ 10,  75, 209]]) tensor([210])
tensor([[ 10,   2,  62,  63,   3, 285,   5, 286]]) tensor([287])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([52])
tensor([[ 10,  75,   3, 298,  19, 299]]) tensor([300])
tensor([[ 10,  11, 190, 159, 191]]) tensor([192])
tensor([[ 10,  11, 158, 159, 160]]) tensor([161])
tensor([[  1,   2,   3,   4,   5, 281]]) tensor([282])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([106])
tensor([[  1,   2,   3,  69,   5, 156]]) tensor([157])
tensor([[  1,   2,   3, 181, 182, 183, 184]]) tensor([185])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([114])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([134])
tensor([[ 42,  86,  87, 243, 244,  19,  39, 245]]) tensor([246])

In [35]:
import torch.nn as nn

In [37]:
class Network(nn.Module):

  def __init__(self,vocab_size ):
    super().__init__()

    self.embedding=nn.Embedding(vocab_size,embedding_dim=60)
    self.rnn = nn.RNN(60,128,batch_first=True)
    self.fc = nn.Linear(128,vocab_size)

  def forward(self,question):
    embedded_question = self.embedding(question)
    hidden,final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

In [49]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [42]:
learning_rate = 0.001
epochs = 200

In [43]:
model = Network(len(vocab))

In [44]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [45]:
# training loop

for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,324) - (1)
    loss = criterion(output, answer[0])

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 522.126061
Epoch: 2, Loss: 401.672246
Epoch: 3, Loss: 285.143569
Epoch: 4, Loss: 194.144117
Epoch: 5, Loss: 119.012067
Epoch: 6, Loss: 67.887553
Epoch: 7, Loss: 41.625174
Epoch: 8, Loss: 26.556608
Epoch: 9, Loss: 18.386896
Epoch: 10, Loss: 13.222540
Epoch: 11, Loss: 10.039887
Epoch: 12, Loss: 7.701115
Epoch: 13, Loss: 6.213035
Epoch: 14, Loss: 5.204472
Epoch: 15, Loss: 4.333184
Epoch: 16, Loss: 3.711536
Epoch: 17, Loss: 3.210122
Epoch: 18, Loss: 2.817637
Epoch: 19, Loss: 2.483774
Epoch: 20, Loss: 2.220196
Epoch: 21, Loss: 1.990471
Epoch: 22, Loss: 1.785305
Epoch: 23, Loss: 1.613357
Epoch: 24, Loss: 1.460696
Epoch: 25, Loss: 1.332195
Epoch: 26, Loss: 1.218125
Epoch: 27, Loss: 1.116750
Epoch: 28, Loss: 1.028226
Epoch: 29, Loss: 0.947788
Epoch: 30, Loss: 0.877153
Epoch: 31, Loss: 0.809152
Epoch: 32, Loss: 0.751882
Epoch: 33, Loss: 0.698010
Epoch: 34, Loss: 0.651712
Epoch: 35, Loss: 0.605587
Epoch: 36, Loss: 0.564105
Epoch: 37, Loss: 0.528008
Epoch: 38, Loss: 0.494319
Epoch: 39, Loss: 0.462552
Epoch: 40, Loss: 0.433563
Epoch: 41, Loss: 0.406804
Epoch: 42, Loss: 0.382216
Epoch: 43, Loss: 0.359598
Epoch: 44, Loss: 0.337888
Epoch: 45, Loss: 0.318615
Epoch: 46, Loss: 0.300512
Epoch: 47, Loss: 0.282845
Epoch: 48, Loss: 0.267288
Epoch: 49, Loss: 0.251914
Epoch: 50, Loss: 0.238231
Epoch: 51, Loss: 0.224966
Epoch: 52, Loss: 0.212723
Epoch: 53, Loss: 0.201363
Epoch: 54, Loss: 0.190434
Epoch: 55, Loss: 0.180305
Epoch: 56, Loss: 0.170897
Epoch: 57, Loss: 0.161661
Epoch: 58, Loss: 0.153380
Epoch: 59, Loss: 0.145352
Epoch: 60, Loss: 0.138036
Epoch: 61, Loss: 0.130894
Epoch: 62, Loss: 0.124333
Epoch: 63, Loss: 0.117792
Epoch: 64, Loss: 0.111898
Epoch: 65, Loss: 0.106367
Epoch: 66, Loss: 0.101062
Epoch: 67, Loss: 0.096034
Epoch: 68, Loss: 0.091337
Epoch: 69, Loss: 0.086759
Epoch: 70, Loss: 0.082440
Epoch: 71, Loss: 0.078558
Epoch: 72, Loss: 0.074651
Epoch: 73, Loss: 0.070952
Epoch: 74, Loss: 0.067540
Epoch: 75, Loss: 0.064299
Epoch: 76, Loss: 0.061206
Epoch: 77, Loss: 0.058241
Epoch: 78, Loss: 0.055570
Epoch: 79, Loss: 0.052875
Epoch: 80, Loss: 0.050244
Epoch: 81, Loss: 0.047900
Epoch: 82, Loss: 0.045648
Epoch: 83, Loss: 0.043441
Epoch: 84, Loss: 0.041484
Epoch: 85, Loss: 0.039462
Epoch: 86, Loss: 0.037616
Epoch: 87, Loss: 0.035817
Epoch: 88, Loss: 0.034165
Epoch: 89, Loss: 0.032544
Epoch: 90, Loss: 0.031012
Epoch: 91, Loss: 0.029547
Epoch: 92, Loss: 0.028198
Epoch: 93, Loss: 0.026865
Epoch: 94, Loss: 0.025624
Epoch: 95, Loss: 0.024455
Epoch: 96, Loss: 0.023305
Epoch: 97, Loss: 0.022233
Epoch: 98, Loss: 0.021202
Epoch: 99, Loss: 0.020248
Epoch: 100, Loss: 0.019303
Epoch: 101, Loss: 0.018386
Epoch: 102, Loss: 0.017566
Epoch: 103, Loss: 0.016734
Epoch: 104, Loss: 0.015972
Epoch: 105, Loss: 0.015245
Epoch: 106, Loss: 0.014541
Epoch: 107, Loss: 0.013877
Epoch: 108, Loss: 0.013227
Epoch: 109, Loss: 0.012631
Epoch: 110, Loss: 0.012050
Epoch: 111, Loss: 0.011506
Epoch: 112, Loss: 0.010982
Epoch: 113, Loss: 0.010478
Epoch: 114, Loss: 0.010019
Epoch: 115, Loss: 0.009549
Epoch: 116, Loss: 0.009114
Epoch: 117, Loss: 0.008699
Epoch: 118, Loss: 0.008305
Epoch: 119, Loss: 0.007931
Epoch: 120, Loss: 0.007571
Epoch: 121, Loss: 0.007227
Epoch: 122, Loss: 0.006902
Epoch: 123, Loss: 0.006587
Epoch: 124, Loss: 0.006287
Epoch: 125, Loss: 0.006005
Epoch: 126, Loss: 0.005735
Epoch: 127, Loss: 0.005474
Epoch: 128, Loss: 0.005229
Epoch: 129, Loss: 0.004995
Epoch: 130, Loss: 0.004763
Epoch: 131, Loss: 0.004552
Epoch: 132, Loss: 0.004344
Epoch: 133, Loss: 0.004144
Epoch: 134, Loss: 0.003962
Epoch: 135, Loss: 0.003790
Epoch: 136, Loss: 0.003616
Epoch: 137, Loss: 0.003449
Epoch: 138, Loss: 0.003293
Epoch: 139, Loss: 0.003144
Epoch: 140, Loss: 0.003011
Epoch: 141, Loss: 0.002869
Epoch: 142, Loss: 0.002741
Epoch: 143, Loss: 0.002621
Epoch: 144, Loss: 0.002503
Epoch: 145, Loss: 0.002386
Epoch: 146, Loss: 0.002282
Epoch: 147, Loss: 0.002180
Epoch: 148, Loss: 0.002081
Epoch: 149, Loss: 0.001987
Epoch: 150, Loss: 0.001900
Epoch: 151, Loss: 0.001814
Epoch: 152, Loss: 0.001732
Epoch: 153, Loss: 0.001654
Epoch: 154, Loss: 0.001579
Epoch: 155, Loss: 0.001508
Epoch: 156, Loss: 0.001441
Epoch: 157, Loss: 0.001375
Epoch: 158, Loss: 0.001314
Epoch: 159, Loss: 0.001256
Epoch: 160, Loss: 0.001199
Epoch: 161, Loss: 0.001148
Epoch: 162, Loss: 0.001097
Epoch: 163, Loss: 0.001047
Epoch: 164, Loss: 0.000999
Epoch: 165, Loss: 0.000955
Epoch: 166, Loss: 0.000912
Epoch: 167, Loss: 0.000872
Epoch: 168, Loss: 0.000832
Epoch: 169, Loss: 0.000797
Epoch: 170, Loss: 0.000760
Epoch: 171, Loss: 0.000726
Epoch: 172, Loss: 0.000695
Epoch: 173, Loss: 0.000663
Epoch: 174, Loss: 0.000635
Epoch: 175, Loss: 0.000605
Epoch: 176, Loss: 0.000577
Epoch: 177, Loss: 0.000551
Epoch: 178, Loss: 0.000527
Epoch: 179, Loss: 0.000504
Epoch: 180, Loss: 0.000481
Epoch: 181, Loss: 0.000459
Epoch: 182, Loss: 0.000439
Epoch: 183, Loss: 0.000422
Epoch: 184, Loss: 0.000401
Epoch: 185, Loss: 0.000383
Epoch: 186, Loss: 0.000365
Epoch: 187, Loss: 0.000349
Epoch: 188, Loss: 0.000334
Epoch: 189, Loss: 0.000320
Epoch: 190, Loss: 0.000304
Epoch: 191, Loss: 0.000290
Epoch: 192, Loss: 0.000278
Epoch: 193, Loss: 0.000266
Epoch: 194, Loss: 0.000254
Epoch: 195, Loss: 0.000243
Epoch: 196, Loss: 0.000232
Epoch: 197, Loss: 0.000221
Epoch: 198, Loss: 0.000211
Epoch: 199, Loss: 0.000201
Epoch: 200, Loss: 0.000194

In [46]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [47]:
predict(model, "What is the largest planet in our solar system?")

jupiter

In [48]:
list(vocab.keys())[7]

'paris'